-- =====================================================================
-- DEPRECATED — do not run.
-- =====================================================================
--
-- This file used to contain a parallel CREATE TABLE definition of
-- bank_transactions, bank_transaction_matches, and
-- bank_transaction_review_events that conflicted with the
-- ALTER-based migration in 005_bank_review_and_matching.sql.
--
-- The two files used incompatible column conventions for
-- bank_transaction_matches:
--
--   This file (deprecated):
--     target_table, amount_matched, match_status = 'active'
--
--   005_bank_review_and_matching.sql (canonical):
--     target_table_name, matched_amount, active = TRUE
--
-- The live database has the canonical schema. The whole running
-- application — services.py, services_*.py, services_month_end_close.py,
-- and every route handler — uses the canonical column names.
--
-- This file is kept on disk so any historical reference to "005_*"
-- still resolves to a file, but it intentionally contains no DDL.
-- See backend/sql/000_baseline_schema_audit.md for the full rationale.
-- =====================================================================
