import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service — BookWize',
  description:
    'Terms of Service and End User License Agreement for BookWize, the bookkeeping automation service for Canadian Home Hardware dealers.',
};

const LAST_UPDATED = 'May 25, 2026';

export default function TermsPage() {
  return (
    <article className="container mx-auto max-w-3xl px-4 py-12">
      <Link
        href="/"
        className="inline-flex items-center gap-1 text-sm text-slate hover:text-ledger-blue mb-6"
      >
        <ArrowLeft className="h-4 w-4" /> Back to home
      </Link>

      <h1 className="text-h1 font-extrabold text-deep-navy">
        Terms of Service
      </h1>
      <p className="text-sm text-slate mt-2">Last updated {LAST_UPDATED}</p>

      <Section title="1. Acceptance of terms">
        <p>
          These Terms of Service ("Terms") form a binding agreement
          between you ("Customer," "you") and BookWize ("BookWize," "we,"
          "us"). By creating an account, accessing, or using the BookWize
          service ("the Service"), you agree to be bound by these Terms
          and by our{' '}
          <Link href="/privacy" className="text-ledger-blue hover:underline">
            Privacy Policy
          </Link>
          . If you do not agree, do not use the Service.
        </p>
      </Section>

      <Section title="2. Description of the service">
        <p>
          BookWize is a software-as-a-service bookkeeping automation
          platform designed for Canadian Home Hardware dealers. It helps
          you import accounting data from QuickBooks Online, classify
          bank transactions, manage HH accounts payable, run payroll
          calculations, perform period-end close workflows, and generate
          financial reports. Features evolve over time and may be added,
          changed, or removed.
        </p>
      </Section>

      <Section title="3. Account registration and security">
        <p>
          You must provide accurate information when registering and keep
          it current. You are responsible for safeguarding your
          credentials and for all activity that occurs under your
          account. Notify us immediately at{' '}
          <a
            href="mailto:support@bookwize.ca"
            className="text-ledger-blue hover:underline"
          >
            support@bookwize.ca
          </a>{' '}
          if you suspect unauthorized access.
        </p>
      </Section>

      <Section title="4. Customer responsibilities">
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Accurate data.</strong> You are responsible for the
            accuracy of data you upload, import, or otherwise provide to
            the Service. BookWize is a tool that processes the data you
            give it; the underlying accounting decisions remain yours.
          </li>
          <li>
            <strong>QBO connection.</strong> If you use the QuickBooks
            integration, you are responsible for keeping your QBO
            connection active, for selecting the correct QBO company
            file, and for ensuring you have authority to grant BookWize
            access to that file.
          </li>
          <li>
            <strong>Review of outputs.</strong> Journal entries,
            categorizations, accruals, and reports generated by the
            Service — including any produced by AI features — must be
            reviewed by a qualified person (you, your bookkeeper, or your
            accountant) before being relied on for tax filings,
            financial reporting, or other binding decisions.
          </li>
          <li>
            <strong>Compliance.</strong> You will use the Service in
            accordance with all applicable Canadian laws, including
            CRA / tax requirements and PIPEDA.
          </li>
        </ul>
      </Section>

      <Section title="5. Plans, fees, and billing">
        <p>
          The BookWize Professional plan is billed at CAD $399 per month
          per store, unless a different plan or price is agreed in
          writing. Billing is handled through Stripe; by subscribing you
          authorize recurring charges to your selected payment method
          until you cancel. Fees are non-refundable except where required
          by law. We may change pricing on at least 30 days' notice; the
          new price applies at your next renewal.
        </p>
      </Section>

      <Section title="6. Free trials">
        <p>
          We may offer a free trial at our discretion. At the end of the
          trial, your subscription automatically converts to a paid plan
          unless you cancel before the trial ends.
        </p>
      </Section>

      <Section title="7. Intellectual property">
        <p>
          BookWize and its content (excluding your data) are owned by
          BookWize and protected by Canadian and international
          intellectual-property laws. We grant you a non-exclusive,
          non-transferable, revocable license to access and use the
          Service for your internal business operations during your
          subscription. You retain all rights to your data.
        </p>
      </Section>

      <Section title="8. AI-generated content">
        <p>
          Some Service features use large-language-model providers to
          suggest classifications, draft entries, or answer questions.
          These outputs are probabilistic and may be wrong. You are
          responsible for reviewing them before accepting. BookWize does
          not warrant that AI outputs will be accurate, complete, or
          appropriate for your tax or accounting situation.
        </p>
      </Section>

      <Section title="9. Limitation of liability">
        <p>
          The Service is provided "as is" and "as available." To the
          maximum extent permitted by law, BookWize disclaims all
          warranties, express or implied, including warranties of
          merchantability, fitness for a particular purpose, and
          non-infringement.
        </p>
        <p className="mt-3">
          BookWize is not a public accounting firm and does not provide
          accounting, tax, or legal advice. You acknowledge that
          bookkeeping automation does not substitute for review by a
          qualified accountant. BookWize is not liable for errors in
          financial statements, tax filings, or other reports that
          originate from data you provided or from your acceptance of an
          automated suggestion.
        </p>
        <p className="mt-3">
          To the maximum extent permitted by law, BookWize's total
          aggregate liability arising out of or related to these Terms
          will not exceed the amount you paid us in the twelve months
          immediately preceding the event giving rise to the claim. We
          will not be liable for any indirect, incidental, special,
          consequential, or punitive damages, or any lost profits,
          revenue, or data, even if we have been advised of the
          possibility of such damages.
        </p>
      </Section>

      <Section title="10. Indemnification">
        <p>
          You agree to defend, indemnify, and hold harmless BookWize
          against any claims arising from (a) your use of the Service,
          (b) your data, or (c) your violation of these Terms.
        </p>
      </Section>

      <Section title="11. Termination">
        <p>
          You may cancel your subscription at any time through the in-app
          billing portal; access continues until the end of your current
          paid period. We may suspend or terminate your access if you
          materially breach these Terms, fail to pay, or use the Service
          in a way that risks harm to other customers or to us. Upon
          termination, you may export your data for 30 days; after that,
          we may delete it.
        </p>
      </Section>

      <Section title="12. Changes to the service or to these terms">
        <p>
          We may modify the Service or these Terms from time to time. For
          material changes to the Terms we will provide notice in the app
          or by email at least 30 days before they take effect. Continued
          use of the Service after that date constitutes acceptance.
        </p>
      </Section>

      <Section title="13. Governing law and venue">
        <p>
          These Terms are governed by the laws of the Province of
          Ontario and the federal laws of Canada applicable therein,
          without regard to conflict-of-laws principles. The courts
          located in Toronto, Ontario have exclusive jurisdiction over
          any dispute arising out of or relating to these Terms, except
          that either party may seek injunctive relief in any court of
          competent jurisdiction.
        </p>
      </Section>

      <Section title="14. Contact">
        <p>
          Questions about these Terms? Email{' '}
          <a
            href="mailto:support@bookwize.ca"
            className="text-ledger-blue hover:underline"
          >
            support@bookwize.ca
          </a>
          .
        </p>
      </Section>
    </article>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8 text-ink leading-relaxed">
      <h2 className="text-h3 font-bold text-deep-navy mb-2">{title}</h2>
      <div className="space-y-2">{children}</div>
    </section>
  );
}
